<%@ Page Title="" Language="C#" MasterPageFile="~/User/User.master" AutoEventWireup="true" CodeFile="mycontacts.aspx.cs" Inherits="User_mycontacts" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            width: 204px;
            font-weight: bold;
            font-size: large;
        }
        .style3
        {
            width: 606px;
        }
        .style4
        {
            font-size: large;
        }
        .style5
        {
            width: 606px;
            font-size: large;
        }
        .style6
        {
            width: 353px;
        }
        .style9
        {
        }
        .style10
        {
            width: 1419px;
        }
        .style11
        {
            width: 679px;
        }
        .style12
        {
            width: 154px;
        }
        .style13
        {
            font-weight: bold;
            font-size: large;
        }
        .style14
        {
            width: 679px;
            font-size: large;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
        <table class="style1">
            <tr>
                <td colspan="3">
                    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
                    </asp:ToolkitScriptManager>
                </td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style10" colspan="3">
                    <asp:Panel ID="Panel3" runat="server" Visible="False">
                        <table class="style1">
                            <tr>
                                <td class="style11">
                                    <asp:GridView ID="gvcontact" runat="server" AutoGenerateColumns="False" 
                                        AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" 
                                        BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" 
                                        GridLines="Horizontal" Caption="My Contacts" CaptionAlign="Top" 
                                        CssClass="style13" onrowdeleting="gvcontact_RowDeleting" 
                                        AllowPaging="True" onpageindexchanging="gvcontact_PageIndexChanging" 
                                        PageSize="8">
                                        <Columns>
                                            <asp:TemplateField>
                                                <ItemTemplate>
                                                    <asp:CheckBox ID="CheckBox1" runat="server" 
                                                        oncheckedchanged="CheckBox1_CheckedChanged" AutoPostBack="True" />
                                                    
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:BoundField DataField="uname" HeaderText="User Name" />
                                            <asp:TemplateField HeaderText="Name">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblfname" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                                                    &nbsp;<asp:Label ID="lbllname" runat="server" Text='<%# Bind("lname") %>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:BoundField DataField="city" HeaderText="Place" />
                                        </Columns>
                                        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                                        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                                        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                                        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                                        <SortedAscendingCellStyle BackColor="#F7F7F7" />
                                        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                                        <SortedDescendingCellStyle BackColor="#E5E5E5" />
                                        <SortedDescendingHeaderStyle BackColor="#242121" />
                                    </asp:GridView>
                                </td>
                                <td class="style12" colspan="2">
                                    <asp:ListBox ID="lbmembers" runat="server" Height="166px" Width="261px" 
                                        BackColor="#CCFFCC" ForeColor="#000066">
                                    </asp:ListBox>
                                </td>
                                <td>
                                    &nbsp;</td>
                            </tr>
                            <tr>
                                <td class="style14">
                                    <b><span class="style4">Existing Groups :&nbsp; </span></b>
                                    <asp:DropDownList ID="ddlgroup" runat="server" CssClass="style13" 
                                        Height="23px" Width="115px" AutoPostBack="True" 
                                        onselectedindexchanged="DropDownList1_SelectedIndexChanged" Visible="False">
                                        <asp:ListItem>Select</asp:ListItem>
                                    </asp:DropDownList>
                                </td>
                                <td class="style12">
                                    <asp:Button ID="Button3" runat="server" onclick="Button3_Click" 
                                        Text="Create a Group" />
                                    <asp:RoundedCornersExtender ID="Button3_RoundedCornersExtender" runat="server" 
                                        Enabled="True" Radius="10" TargetControlID="Button3">
                                    </asp:RoundedCornersExtender>
                                </td>
                                <td class="style12">
                                    <asp:Button ID="Button4" runat="server" onclick="Button4_Click" 
                                        Text="Remove From List" />
                                    <asp:RoundedCornersExtender ID="Button4_RoundedCornersExtender" runat="server" 
                                        Enabled="True" Radius="10" TargetControlID="Button4">
                                    </asp:RoundedCornersExtender>
                                </td>
                                <td>
                                    &nbsp;</td>
                            </tr>
                        </table>
                        <br />

                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td class="style9">
                    &nbsp;</td>
                <td colspan="2">
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style9">
                    &nbsp;</td>
                <td>
                    <asp:TextBox ID="txtsearch" runat="server" Height="26px" 
                        style="margin-left: 307px" Width="333px" 
          ></asp:TextBox>
                    <asp:TextBoxWatermarkExtender ID="txtsearch_TextBoxWatermarkExtender" 
                        runat="server" Enabled="True" TargetControlID="txtsearch" 
                        WatermarkText="Search For Friends...">
                    </asp:TextBoxWatermarkExtender>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="Button5" runat="server" Text="Search" Width="123px" 
                        onclick="Button5_Click" />
                    &nbsp;
                    <asp:Label ID="lblmsg" runat="server" Font-Bold="True" Font-Size="13pt" 
                        ForeColor="Red"></asp:Label>
                    <br />
                </td>
                <td>
                    &nbsp;</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class="style9">
                    &nbsp;</td>
                <td colspan="2">
                    <asp:Panel ID="Panel1" runat="server" Height="224px" Visible="False">
                        <table class="style1">
                            <tr>
                                <td class="style2">
                                    User Name</td>
                                <td class="style4">
                                    <b>:</b></td>
                                <td class="style3">
                                    <asp:Label ID="lbluser" runat="server" CssClass="style4"></asp:Label>
                                </td>
                                <td rowspan="2">
                                    <asp:Panel ID="Panel2" runat="server" CssClass="style4" Height="135px" 
                                        Width="149px">
                                        <asp:Image ID="Image1" runat="server" Height="129px" Width="146px" />
                                    </asp:Panel>
                                </td>
                            </tr>
                            <tr>
                                <td class="style2">
                                    Name</td>
                                <td class="style4">
                                    <b>:</b></td>
                                <td class="style3">
                                    <asp:Label ID="lblfirst" runat="server" CssClass="style4"></asp:Label>
                                    &nbsp;<asp:Label ID="lbllast" runat="server" Text="Label"></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td class="style2">
                                    Place</td>
                                <td class="style4">
                                    <b>:</b></td>
                                <td class="style3">
                                    <asp:Label ID="lblplace" runat="server" CssClass="style4"></asp:Label>
                                </td>
                                <td class="style4">
                                    &nbsp;</td>
                            </tr>
                        </table>
                        <table class="style1">
                            <tr>
                                <td class="style2">
                                    &nbsp;</td>
                                <td class="style6">
                                    <b></b>
                                </td>
                                <td class="style5">
                                    <asp:Button ID="Button2" runat="server" Text="Add To Contacts" 
                                        onclick="Button2_Click" />
                                    <asp:RoundedCornersExtender ID="Button2_RoundedCornersExtender" runat="server" 
                                        Enabled="True" Radius="10" TargetControlID="Button2">
                                    </asp:RoundedCornersExtender>
                                </td>
                                <td class="style4">
                                    &nbsp;</td>
                            </tr>
                        </table>
                    </asp:Panel>
                    <asp:RoundedCornersExtender ID="Panel1_RoundedCornersExtender" runat="server" 
                        Enabled="True" Radius="15" TargetControlID="Panel1">
                    </asp:RoundedCornersExtender>
                </td>
                <td>
                    &nbsp;</td>
            </tr>
        </table>
        <br />
    </p>
    <p>
    </p>
</asp:Content>

